spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8089
  servlet:
    context-path: /common-upload

logging:
  level:
    uk.nhs.hee.tis: ${LOGGING_LEVEL:INFO}
  file:
    name: ${LOG_DIR:${HOME}}/common-upload.log

management:
  endpoints:
    web:
      exposure:
        include: info, health, loggers
  server:
    servlet:
      context-path: /management
    add-application-context-header: false

app:
  error:
    exchange: "ex.error"
    limit.retries: true

sentry:
  dsn: ${SENTRY_DSN:}
  environment: ${SENTRY_ENVIRONMENT:}

cloud:
  aws:
    sns:
      delete-event-topic: ${SNS_DELETE_EVENT_TOPIC_ARN:}
