server:
  port: 8089
  servlet:
    context-path: /common-upload

logging:
  level:
    com.transformuk: ${LOGGING_LEVEL:INFO}
  file:
    name: ${LOG_DIR:${HOME}}/common-upload.log

management:
  endpoints:
    web:
      exposure:
        include: info, health, loggers
  server:
    servlet:
      context-path: /management
    add-application-context-header: false

app:
  error:
    exchange: "ex.error"
    limit.retries: true

  aws:
    access:
      key:
        id: ${AWS_ACCESS_KEY_ID:AKIAWISJGQ6JTHSHGYKI}
    secret:
      access:
        key: ${AWS_SECRET_ACCESS_KEY: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}
