name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: health-education-england/.github/.github/workflows/build-gradle.yml@main
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}

  deploy-core-preprod:
    needs: build
    uses: health-education-england/.github/.github/workflows/deploy.yml@main
    with:
      cluster-prefix: tis
      environment: preprod
      service-name: tis-core-common-upload

  deploy-core-prod:
    needs: deploy-core-preprod
    uses: health-education-england/.github/.github/workflows/deploy.yml@main
    with:
      cluster-prefix: tis
      environment: prod
      service-name: tis-core-common-upload

  deploy-reval-preprod:
    needs: build
    uses: health-education-england/.github/.github/workflows/deploy.yml@main
    with:
      cluster-prefix: revalidation
      environment: preprod
      service-name: tis-common-upload

  deploy-reval-prod:
    needs: deploy-reval-preprod
    uses: health-education-england/.github/.github/workflows/deploy.yml@main
    with:
      cluster-prefix: revalidation
      environment: prod
      service-name: tis-common-upload
